# Generated by Django 2.0.7 on 2018-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(max_length=100)),
                ('bb', models.CharField(max_length=30)),
            ],
        ),
    ]
